apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway-controller
spec:
  replicas: 2
  selector:
    name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
        - name: gateway
          image: iceboy1818/microservice-gate-way:latest
          ports:
            - containerPort: 80
